### ISSUE TITLE
EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by timoisalive** [DigitalStrawberry/ANE-Bugsnag#2] opened 2016-01-07 10:39 UTC
Hi there, and thank you for sharing this ANE! :)

I'm not 100% sure if this is a Bugsnag ANE issue, but I thought I'd ask if you guys understand better.

Our users are getting some EXC_BAD_ACCESS exceptions in our Thisissand iOS app, and in Bugsnag I can see stacktraces similar to the example below. They all have the line which points to ANEBugsnag.

I don't think we've had similar issues before, but then again, I can't be sure cause we weren't using Bugsnag before and weren't aware of the native iOS exceptions..

Thanks for any help! :)

EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x18. 
    thisissand main
    unknown main
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/363b8a04-adb7-4671-a2e9-e7ca41dd2a8c/libcom.bugsnag.ANEBugsnag.a(FRETypeUtils.o)
    Frameworks/QuartzCore.framework/QuartzCore _ZN2CA7Display15DisplayLinkItem8dispatchEv
    Frameworks/QuartzCore.framework/QuartzCore _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy
    Frameworks/IOKit.framework/Versions/A/IOKit IODispatchCalloutFromCFMessage
    Frameworks/CoreFoundation.framework/CoreFoundation __CFMachPortPerform
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRunLoopDoSource1
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices GSEventRunModal
    Frameworks/UIKit.framework/UIKit UIApplicationMain
    thisissand main
    /usr/lib/system/libdyld.dylib start

**Comment by timoisalive** [comment] 2016-01-07 10:44
Oh, also, I was trying to debug the issue by uploading the dsym file to Bugsnag, but wasn't able to do it, the curl script just returns "Still missing:" and two id's...

**Comment by ecornbower** [comment] 2016-01-09 01:53
Thanks for letting us know about this issue. We'll look more into it and get back to you. Were you able to reproduce this crash yourself, or is it just showing up in the Bugsnag logs?

**Comment by timoisalive** [comment] 2016-03-10 08:10
Hey there! Sorry I never got your reply, but no, I haven't been able to repro myself, it's just the bugsnag logs I'm relying on. Anyhow, the problem still persists...

**Comment by timoisalive** [comment] 2016-03-16 13:53
I'm back trying to debug this issue.

It seems I've got two types of EXC_BAD_ACCESS exceptions. The others point to ANE-Bugsnag and the others to ANE-Google-Analytics, and they both mention "Attempted to dereference garbage pointer".

I have managed to get the app crashing once, but not another time. This was due to ANE-Google-Analytics, I suspect, because the only method I was able to recognize from the threads was "trackSocial" which is part of the ANE-Google-Anaytics.

Also, I was able to upload the dSYM file to bugsnag, but it didn't do anything, the stacktraces still prompt me to upload the dSYM. I wonder if the dSYM needs to be the exact one which was created when packaging the App Store release version... I don't have it around anymore and I recreated the dSYM by packaging the ipa another time, from the same repository version though.

I'm thinking I'll try another ANE for GA, to see if it would fix the other half of the crashes, but the ones pointing to ANE-Bugsnag will probably still remain...

Any ideas or help would be highly appreciated, thanks! :)

**Comment by ecornbower** [comment] 2016-03-17 14:58
The uploaded dSYM does need to be the same one created when you originally packaged the app. What we do is commit the generated dSYM to version control each time we release an update, tagged with the app version number. This makes it easier to grab the dSYM file if you ever need it again.

I'll do some more digging and see if I can figure out where the crash is coming from.

**Comment by timoisalive** [comment] 2016-03-17 15:04
Cool, thanks a lot.

That's what I figured abut the dSYM. I'm uploading the dSYM of our new release to the repo as I'm writing this... :)

I'll let you know if I succeeded in getting rid of the (possible) GA ANE crashes!

And also, I did start a discussion of the crash in Starling Forum as well:

http://forum.starling-framework.org/topic/exc_bad_access-crashes-on-ios-due-to-anes

**Comment by ecornbower** [comment] 2016-03-17 16:10
Great, let me know if you're able to get line numbers or method calls from the crashes. That will greatly help in tracking down exactly what is causing this.

**Comment by timoisalive** [comment] 2016-03-23 20:20
So the new version is live now, and I was able to upload dSYM into Bugsnag. However

`dwarfdump --uuid thisissand.app/thisissand`

didn't return UUID for armv7, only for arm64.... But even the error reports for arm64 (which don't request to upload dSYM anymore) don't display any more information than before. Am I not getting something...?

Stacktrace:

```
EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x18. 
    thisissand main
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/80d690a1-4de2-4be8-88d1-81474d5d068c/libcom.bugsnag.ANEBugsnag.a(FRETypeUtils.o)
    Frameworks/QuartzCore.framework/QuartzCore <redacted>
    Frameworks/QuartzCore.framework/QuartzCore <redacted>
    Frameworks/IOKit.framework/Versions/A/IOKit IODispatchCalloutFromCFMessage
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices GSEventRunModal
    Frameworks/UIKit.framework/UIKit UIApplicationMain
    thisissand main
    /usr/lib/system/libdyld.dylib <redacted>
```

Error:

```
address
24
mach
{
  "code": 24,
  "code_name": "KERN_MEMORY_DATA_MOVED",
  "exception": 1,
  "exception_name": "EXC_BAD_ACCESS",
  "subcode": 8
}
signal
{
  "code": 0,
  "code_name": "BUS_NOOP",
  "name": "SIGBUS",
  "signal": 10
}
type
mach
```

**Comment by ecornbower** [comment] 2016-03-28 02:22
Thanks for your patience with this, we are still looking into it. We've been a bit busy due to the Easter holiday this week.

**Comment by timoisalive** [comment] 2016-03-29 08:38
No problem Kevin,

thanks already for looking into it, that's very nice of you!

**Comment by timoisalive** [comment] 2016-10-05 07:20
Hi Kevin,

I've still not found answers to this issue, we're still receiving this kind of error reports from a small percentage of our iOS users:

```
EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x18. 
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/d20422bf-b5b3-43b1-a9d6-12a263a3fa57/libcom.bugsnag.ANEBugsnag.a(ANEBugsnag.o)
    thisissand main
    thisissand main
    thisissand main
    thisissand main
    thisissand main
    thisissand main
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/d20422bf-b5b3-43b1-a9d6-12a263a3fa57/libcom.bugsnag.ANEBugsnag.a(ANEBugsnag.o)
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/d20422bf-b5b3-43b1-a9d6-12a263a3fa57/libcom.bugsnag.ANEBugsnag.a(ANEBugsnag.o)
    thisissand /var/folders/h7/b3r397290c75zjcqnb1kbdnm0000gn/T/d20422bf-b5b3-43b1-a9d6-12a263a3fa57/libcom.bugsnag.ANEBugsnag.a(ANEBugsnag.o)
    Frameworks/UIKit.framework/UIKit -[UIApplication _terminateWithStatus:]
    Frameworks/UIKit.framework/UIKit __102-[UIApplication _handleApplicationDeactivationWithScene:shouldForceExit:transitionContext:completion:]_block_invoke.2098
    Frameworks/UIKit.framework/UIKit _runAfterCACommitDeferredBlocks
    Frameworks/UIKit.framework/UIKit _cleanUpAfterCAFlushAndRunDeferredBlocks
    Frameworks/UIKit.framework/UIKit _afterCACommitHandler
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRunLoopDoObservers
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices GSEventRunModal
    Frameworks/UIKit.framework/UIKit -[UIApplication _run]
    Frameworks/UIKit.framework/UIKit UIApplicationMain
    thisissand main
    /usr/lib/system/libdyld.dylib start
```

The news is that I realized that this crash happens after the app is being suspended:

```
duration
25482100
durationInForeground
25481500
id
com.beigeelephant.thisissand
inForeground
false
name
thisissand
releaseStage
production
stats
{
  "active_time_since_last_crash": 25481.5,
  "active_time_since_launch": 25481.5,
  "application_active": false,
  "application_in_foreground": false,
  "background_time_since_last_crash": 0.555856,
  "background_time_since_launch": 0.555856,
  "launches_since_last_crash": 1,
  "sessions_since_last_crash": 1,
  "sessions_since_launch": 1
}
```

In this case the error was thrown pretty much right after suspending, but in some cases it might have taken up to 90 seconds before the error occurring. 

This is the error:

```
address
24
mach
{
  "code": 24,
  "code_name": "KERN_MEMORY_DATA_MOVED",
  "exception": 1,
  "exception_name": "EXC_BAD_ACCESS",
  "subcode": 8
}
signal
{
  "code": 0,
  "code_name": "BUS_NOOP",
  "name": "SIGBUS",
  "signal": 10
}
type
mach
```

Just wanted to share this, in case it rings a bell! Thanks again! :)

**Comment by ecornbower** [comment] 2016-10-06 17:49
Thanks for the update, that is very helpful. We'll be looking into this more.

**Comment by timoisalive** [comment] 2016-10-13 07:21
Hi Kevin, some more information. We've found a user who can irregularly reproduce the crash, and it seems it's happening also without the Bugsnag ANE, so most likely the problem is not in your end.

**Comment by ecornbower** [comment] 2016-10-17 12:10
@timoisalive Thanks for the additional info. I'm going to close this issue but please let us know if you do track the source back to the ANE.

**Closed as completed by ecornbower** 2016-10-17 12:10 UTC
Labels: bug
